[project]
name = "repl-nix-sistema-avaliacao-rg-back"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.0.3",
    "flask-cors>=5.0.0",
    "flask-sqlalchemy>=3.1.1",
]
